# Generated by Django 6.1.1 on 2026-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahayak_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('worker', 'Worker')], default='user', max_length=10),
        ),
    ]
